### ISSUE TITLE
Cannot read property 'initial' of undefined

### ISSUE THREAD

**Issue by bdefore** [erikras/redux-form#20]
Getting this error since updating from 0.5 to 0.7
```
{"error":"TypeError: Cannot read property 'initial' of undefined\n    at ReduxForm.render (/[REDACTED]/node_modules/redux-form/lib/reduxForm.js:67:45)\n    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/[REDACTED]/node_modules/react/lib/ReactCompositeComponent.js:789:34)\n    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/[REDACTED]/node_modules/react/lib/ReactCompositeComponent.js:816:14)\n    at [object Object].wrapper [as _renderValidatedComponent] (/[REDACTED]/node_modules/react/lib/ReactPerf.js:70:21)\n    at [object Object].ReactCompositeComponentMixin.mountComponent (/[REDACTED]/node_modules/react/lib/ReactCompositeComponent.js:237:30)\n    at [object Object].wrapper [as mountComponent] (/[REDACTED]/node_modules/react/lib/ReactPerf.js:70:21)\n    at Object.ReactReconciler.mountComponent (/[REDACTED]/node_modules/react/lib/ReactReconciler.js:38:35)\n    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/[REDACTED]/node_modules/react/lib/ReactMultiChild.js:192:44)\n    at ReactDOMComponent.Mixin._createContentMarkup (/[REDACTED]/node_modules/react/lib/ReactDOMComponent.js:289:32)\n    at ReactDOMComponent.Mixin.mountComponent (/[REDACTED]/node_modules/react/lib/ReactDOMComponent.js:199:12)”}
```

**Comment by gaearon** [comment]
I'm afraid this project hasn't been following semver (but it will now): #19 
0.0.7 introduced a slightly different API: https://github.com/erikras/redux-form/commit/e9b462cbb41bd8df3d27495c9911b9a2155d9b4e
