### ISSUE TITLE
npm run test:codecov not working

### ISSUE THREAD

**Issue by timhwang21** [erikras/redux-form#2432]
Discovered this issue when working on a PR earlier.

```
[15:26]thwang~/Personal/redux-form-thwang/provide-props-to-create-validator->npm run test:codecov
npm info it worked if it ends with ok
npm info using npm@3.10.5
npm info using node@v6.2.2
npm info lifecycle redux-form@6.4.3~pretest:codecov: redux-form@6.4.3
npm info lifecycle redux-form@6.4.3~test:codecov: redux-form@6.4.3

> redux-form@6.4.3 test:codecov /Users/thwang/Personal/redux-form
> cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js

cat: ./coverage/lcov.info: No such file or directory
/Users/thwang/Personal/redux-form/node_modules/codecov.io/lib/getConfiguration.js:27
      throw new Error("unknown service. could not get configuration");
      ^

Error: unknown service. could not get configuration
    at module.exports (/Users/thwang/Personal/redux-form/node_modules/codecov.io/lib/getConfiguration.js:27:13)
    at sendToCodecov (/Users/thwang/Personal/redux-form/node_modules/codecov.io/lib/sendToCodeCov.io.js:11:15)
    at Socket.<anonymous> (/Users/thwang/Personal/redux-form/node_modules/codecov.io/bin/codecov.io.js:14:5)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm info lifecycle redux-form@6.4.3~test:codecov: Failed to exec test:codecov script
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test:codecov"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! redux-form@6.4.3 test:codecov: `cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-form@6.4.3 test:codecov script 'cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-form
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-form
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thwang/Personal/redux-form/npm-debug.log
```

From `npm-debug.log`:

```
14 verbose stack Error: redux-form@6.4.3 test:codecov: `cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid redux-form@6.4.3
16 verbose cwd /Users/thwang/Personal/redux-form
```

**Comment by gustavohenke** [comment]
This script is probably meant to be used in the CI environment only.
