### ISSUE TITLE
Field Level Validation Validator is not a function

### ISSUE THREAD

**Issue by khpatel4991** [erikras/redux-form#2515]
Hi, I have a simple signup form component and Im trying to use field level validation on each field. Everytime I pass `validate` prop on any field, I get this weird error. I'm using next js for server-rendering.

```
TypeError: validator is not a function
    at getError (http://localhost:3000/_next/-/commons.js:25486:19)
    at http://localhost:3000/_next/-/commons.js:25513:19
    at Array.forEach (native)
    at http://localhost:3000/_next/-/commons.js:25511:29
    at Form.validateIfNeeded (http://localhost:3000/_next/-/commons.js:26490:213)
    at Form.componentWillReceiveProps (http://localhost:3000/_next/-/commons.js:26558:18)
    at http://localhost:3000/_next/-/main.js:19132:23
    at measureLifeCyclePerf (http://localhost:3000/_next/-/main.js:18596:12)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:3000/_next/-/main.js:19131:9)**

```

If I remove the validate prop. the page renders as expected.

**Comment by gustavohenke** [comment]
Please provide a reproducible example.

**Comment by khpatel4991** [comment]
It was my mistake with the format. My issue is fixed and I'm closing this issue.

**Comment by atalebagha** [comment]
I'm getting the same error @khpatel4991 could you share the details of your error so maybe it can help me fix the error

**Comment by osiloke** [comment]
I get the same error, it would be nice to know what syntax issue you had
