### ISSUE TITLE
Untouch FieldArray error

### ISSUE THREAD

**Issue by Jakst** [erikras/redux-form#2623]
### Are you submitting a **bug report** or a **feature request**?
Both 

### What is the current behavior?
Error is thrown when calling untouch on a FieldArray

Steps to reproduce:
jsFiddle: [https://jsfiddle.net/j7bdhL6s/7/](https://jsfiddle.net/j7bdhL6s/7/)
1. Open console
2. Click 'Add Member'
3. Put cursor in any of the empty text fields
4. Click 'Untouch fields'
5. Observe following error

`Uncaught Error: Cannot delete non-numerical index from an array
    at deleteInWithPath (https://cdnjs.cloudflare.com/ajax/libs/redux-form/6.2.0/redux-form.js:4615:14)
    at deleteInWithPath (https://cdnjs.cloudflare.com/ajax/libs/redux-form/6.2.0/redux-form.js:4608:39)
    at deleteInWithPath (https://cdnjs.cloudflare.com/ajax/libs/redux-form/6.2.0/redux-form.js:4608:39)
    at deleteIn (https://cdnjs.cloudflare.com/ajax/libs/redux-form/6.2.0/redux-form.js:4633:28)
    at https://cdnjs.cloudflare.com/ajax/libs/redux-form/6.2.0/redux-form.js:3528:24
    at Array.forEach (native)
    at https://cdnjs.cloudflare.com/ajax/libs/redux-form/6.2.0/redux-form.js:3527:13
    at reducer (https://cdnjs.cloudflare.com/ajax/libs/redux-form/6.2.0/redux-form.js:3574:24)
    at https://cdnjs.cloudflare.com/ajax/libs/redux-form/6.2.0/redux-form.js:3590:21
    at https://cdnjs.cloudflare.com/ajax/libs/redux/3.6.0/redux.min.js:1:5926`

### What is the expected behavior?
**Bug**
I guess nothing should output in the console.

**Feature request**
Recursive untouch, meaning if I send untouch on 'members', it will untouch all fields in all rows of the fieldArray.

For example `untouch('members')` would remove touched status of all the following fields:
`members[0].firstName
members[0].lastName
members[1].firstName
members[1].lastName
members[2].firstName
members[2].lastName`

And `untouch('members[0]')` would remove touched status of all the following fields:
`members[0].firstName
members[0].lastName`

**Comment by danielrob** [comment]
Would you mind updating this into an issue each for the bug and feature? (Update this and raise a new?) Will be easier to track :).

**Comment by Jakst** [comment]
Moved feature request to #3314
