### ISSUE TITLE
Error on createPropTypes file in v5.3.5

### ISSUE THREAD

**Issue by davidebianchi** [erikras/redux-form#2824]
### Are you submitting a **bug report** or a **feature request**?

A bug report

### What is the current behavior?

The bug is on the v5.3.5, and it look introduced by the transpilation with babel.
To reproduce, just download the npm package at v5.3.5 and try to use it.
I've tried to clone the repo and build it from local and it works without any issue. Maybe it has been builded with an old version of babel?

### What is the expected behavior?
It runs without error

### Sandbox Link

The createPropTypes.js files in lib is:
```js
var _propTypes = require('prop-types');

var _propTypes2 = _interopRequireDefault(_propTypes);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var any = _propTypes2.default.any,
    bool = _propTypes2.default.bool,
    string = _propTypes2.default.string,
    func = _propTypes2.default.func,
    obj = _propTypes2.default.obj;
```

but it should be:
```js
var _propTypes = require('prop-types');

var _propTypes2 = _interopRequireDefault(_propTypes);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var any = _propTypes2.default.any,
    bool = _propTypes2.default.bool,
    string = _propTypes2.default.string,
    func = _propTypes2.default.func,
    object = _propTypes2.default.object;
```

### What's your environment?

redux-form v5.3.5

### Other information

```
 ./node_modules/redux-form/lib/createPropTypes.js:26
    errors: object, // a map of errors corresponding to structure of form data (result of validation)
            ^
ReferenceError: object is not defined
    at createPropTypes (/opt/atlassian/pipelines/agent/build/node_modules/redux-form/lib/createPropTypes.js:26:13)
    at createAll (/opt/atlassian/pipelines/agent/build/node_modules/redux-form/lib/createAll.js:135:46)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/redux-form/lib/index.js:20:42)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/atlassian/pipelines/agent/build/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```

**Comment by gustavohenke** [comment]
It seems like it was fixed, can you try v5.3.6, please?

**Comment by erikras** [comment]
Yes, this is fixed for sure.

**Comment by davidebianchi** [comment]
Yes, this is fixed. Thanks!
