### ISSUE TITLE
Missing default export in "es" module version of actionTypes

### ISSUE THREAD

**Issue by hoschi** [erikras/redux-form#3509]
### Are you submitting a **bug report** or a **feature request**?

bug

### What is the current behavior?

Error thrown when using tree shaking like suggested here https://redux-form.com/7.1.1/docs/faq/bundlesize.md/ when using `actionTypes` as shown for `actions`.

This should work:
```js
import {actionTypes} from 'redux-form'

const {SET_SUBMIT_SUCCEEDED} = actionTypes;
```

It works in develop build without tree shaking, but fails during prod build:
```
/home/hoschi/repos/gis/frontend/node_modules/@gis-ag/gravity-frontend-buildtools/lib/dynamic-gulp-tasks/webpackBuild.js:41                                    throw new gutil.PluginError('webpack', buildError);                   
      ^                               
Error: ./src/services/formHelper.js   
5:27-38 "export 'default' (imported as 'actionTypes') was not found in 'redux-form/es/actionTypes'                                                          at HarmonyImportSpecifierDependency._getErrors (/home/hoschi/repos/gis/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/home/hoschi/repos/gis/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/home/hoschi/repos/gis/frontend/node_modules/webpack/lib/Compilation.js:694:24)                   
    at Compilation.finish (/home/hoschi/repos/gis/frontend/node_modules/webpack/lib/Compilation.js:552:9)                                                   at applyPluginsParallel.err (/home/hoschi/repos/gis/frontend/node_modules/webpack/lib/Compiler.js:506:17)                                           
    at /home/hoschi/repos/gis/frontend/node_modules/tapable/lib/Tapable.js:289:11                                                                           at _addModuleChain (/home/hoschi/repos/gis/frontend/node_modules/webpack/lib/Compilation.js:498:11)                                                 
    at processModuleDependencies.err (/home/hoschi/repos/gis/frontend/node_modules/webpack/lib/Compilation.js:468:14)                                       at _combinedTickCallback (internal/process/next_tick.js:67:7)           
    at process._tickCallback (internal/process/next_tick.js:98:9)          
```

### What is the expected behavior?
`actionTypes` should be build as `actions` so this error won't appear.

### What's your environment?

redux-form: 7.1.1
npm: 3.10.10
webpack: 3.6.0

**Comment by hoschi** [comment]
hotfix patched from v7.0.3 https://github.com/hoschi/redux-form/tree/hotfix/3509
and build so it can be used as npm dependency https://github.com/hoschi/redux-form/tree/hotfix/3509-build

**Comment by bertho-zero** [comment]
This works for me: https://runkit.com/bertho-zero/59de0d619bf4d50012d3b285

**Comment by hoschi** [comment]
> It works in develop build without
yes, because it isn't configured to use tree shaking. But when this gets transformed to `import actionTypes from 'redux-forms/es/actionTypes'` it fails.

**Comment by hoschi** [comment]
```js
import { SET_SUBMIT_SUCCEEDED } from 'redux-form/es/actionTypes';
```

works
