### ISSUE TITLE
path.lastIndexOf is not a function  deleteInWithCleanUp

### ISSUE THREAD

**Issue by sant527** [erikras/redux-form#3657]
I am getting the below error. I am not using Destroy anywhere.

```
Uncaught TypeError: path.lastIndexOf is not a function
    at deleteInWithCleanUp (http://localhost:3000/static/js/bundle.js:55544:25)
    at http://localhost:3000/static/js/bundle.js:54425:18
    at Array.reduce (native)
    at http://localhost:3000/static/js/bundle.js:54424:33
    at http://localhost:3000/static/js/bundle.js:54452:25
    at combination (http://localhost:3000/static/js/bundle.js:57829:29)
    at computeNextEntry (<anonymous>:2:27469)
    at recomputeStates (<anonymous>:2:27769)
    at <anonymous>:2:31382
    at Object.dispatch (http://localhost:3000/static/js/bundle.js:58066:22)
    at dispatch (<anonymous>:2:31875)
    at http://localhost:3000/static/js/bundle.js:47791:18
    at http://localhost:3000/static/js/bundle.js:57534:7806
    at Object.dispatch (http://localhost:3000/static/js/bundle.js:57562:16)
    at dispatch (<anonymous>:2:1620)
    at http://localhost:3000/static/js/bundle.js:57649:12
    at Form.componentWillUnmount (http://localhost:3000/static/js/bundle.js:55005:15)
    at callComponentWillUnmountWithTimerInDev (http://localhost:3000/static/js/bundle.js:33109:16)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:23291:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:23330:16)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:23187:27)
    at safelyCallComponentWillUnmount (http://localhost:3000/static/js/bundle.js:33117:7)
    at commitUnmount (http://localhost:3000/static/js/bundle.js:33407:13)
    at commitNestedUnmounts (http://localhost:3000/static/js/bundle.js:33271:7)
    at unmountHostComponents (http://localhost:3000/static/js/bundle.js:33328:9)
    at commitDeletion (http://localhost:3000/static/js/bundle.js:33378:5)
    at commitAllHostEffects (http://localhost:3000/static/js/bundle.js:34263:13)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:23291:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:23330:16)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:23187:27)
    at commitAllWork (http://localhost:3000/static/js/bundle.js:34368:9)
    at workLoop (http://localhost:3000/static/js/bundle.js:34679:13)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:23291:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:23330:16)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:23187:27)
    at performWork (http://localhost:3000/static/js/bundle.js:34792:7)
    at batchedUpdates (http://localhost:3000/static/js/bundle.js:35236:9)
    at performFiberBatchedUpdates (http://localhost:3000/static/js/bundle.js:23638:10)
    at stackBatchedUpdates (http://localhost:3000/static/js/bundle.js:23629:10)
    at batchedUpdates (http://localhost:3000/static/js/bundle.js:23643:10)
    at Object.batchedUpdatesWithControlledComponents [as batchedUpdates] (http://localhost:3000/static/js/bundle.js:23656:12)
    at dispatchEvent (http://localhost:3000/static/js/bundle.js:23866:30)
deleteInWithCleanUp @ deleteInWithCleanUp.js:25
(anonymous) @ createReducer.js:528
(anonymous) @ createReducer.js:527
(anonymous) @ createReducer.js:555
combination @ combineReducers.js:120
computeNextEntry @ VM1409:2
recomputeStates @ VM1409:2
(anonymous) @ VM1409:2
dispatch @ createStore.js:165
dispatch @ VM1409:2
(anonymous) @ middleware.js:13
(anonymous) @ redux-logger.js:1
(anonymous) @ index.js:14
dispatch @ VM1409:2
(anonymous) @ bindActionCreators.js:3
componentWillUnmount @ createReduxForm.js:494
callComponentWillUnmountWithTimerInDev @ react-dom.development.js:11117
callCallback @ react-dom.development.js:1299
invokeGuardedCallbackDev @ react-dom.development.js:1338
invokeGuardedCallback @ react-dom.development.js:1195
safelyCallComponentWillUnmount @ react-dom.development.js:11125
commitUnmount @ react-dom.development.js:11415
commitNestedUnmounts @ react-dom.development.js:11279
unmountHostComponents @ react-dom.development.js:11336
commitDeletion @ react-dom.development.js:11386
commitAllHostEffects @ react-dom.development.js:12271
callCallback @ react-dom.development.js:1299
invokeGuardedCallbackDev @ react-dom.development.js:1338
invokeGuardedCallback @ react-dom.development.js:1195
commitAllWork @ react-dom.development.js:12376
workLoop @ react-dom.development.js:12687
callCallback @ react-dom.development.js:1299
invokeGuardedCallbackDev @ react-dom.development.js:1338
invokeGuardedCallback @ react-dom.development.js:1195
performWork @ react-dom.development.js:12800
batchedUpdates @ react-dom.development.js:13244
performFiberBatchedUpdates @ react-dom.development.js:1646
stackBatchedUpdates @ react-dom.development.js:1637
batchedUpdates @ react-dom.development.js:1651
batchedUpdatesWithControlledComponents @ react-dom.development.js:1664
dispatchEvent @ react-dom.development.js:1874
index.js:2177 The above error occurred in the <Form(IngredientForm)> component:
    in Form(IngredientForm) (created by Connect(Form(IngredientForm)))
    in Connect(Form(IngredientForm)) (created by ReduxForm)
    in ReduxForm (created by Connect(ReduxForm))
    in Connect(ReduxForm) (at ItemList.js:519)
    in div (at ItemList.js:497)
    in ItemList (created by Connect(ItemList))
    in Connect(ItemList) (created by Route)
    in Route (created by withRouter(Connect(ItemList)))
    in withRouter(Connect(ItemList)) (created by Route)
    in Route (at Root.js:17)
    in div (at Root.js:16)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (at Root.js:15)
    in Provider (at Root.js:14)
    in Root (at index.js:12)
```

**Comment by sant527** [comment]
I found the answer. I had an if condition whether to load the form or not. If the if condition fails, it doesnt show the form because of which the destroy is called. I changed my logic and now everything is working
